### ISSUE TITLE
ar9331 fft sample mag_info

### ISSUE THREAD

**Issue by hisijie** [mickflemm/ath-info#1]
Hi Nick,

/* The HT20 spectral data has 4 bytes of additional information at it's end.
 *
 * [7:0]: all bins {max_magnitude[1:0], bitmap_weight[5:0]}
 * [7:0]: all bins  max_magnitude[9:2]
 * [7:0]: all bins {max_index[5:0], max_magnitude[11:10]}
 * [3:0]: max_exp (shift amount to size max bin to 8-bit unsigned)
 */
struct ath_ht20_mag_info {
	u8 all_bins[3];
	u8 max_exp;
} __packed;

How do you know there have additional 4 bytes in the end of fft sample and format like that?

**Comment by mickflemm** [comment]
There is no such thing in ath_info, please don't open irrelevant issues.
